server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: dbuser
    password: 12345

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

logging:
  logging:
    file:
      name: logs/inventory-service.log
  level:
    org.hibernate.SQL: DEBUG
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG