server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_db
    username: dbuser
    password: 12345

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: basic
            connectTimeout: 1000
            readTimeout: 3000
          inventory-service:
            connectTimeout: 1000
            readTimeout: 2000

logging:
  file:
    name: logs/order-service.log
  level:
    org.hibernate.SQL: DEBUG
    liquibase: DEBUG
    ru.yandex.practicum.order.feign: DEBUG
