aggregator.kafka.bootstrap-servers=localhost:9092

aggregator.kafka.topic.snapshots-topic=telemetry.snapshots.v1
aggregator.kafka.topic.sensor-topic=telemetry.sensors.v1

aggregator.kafka.consumer.group-id=aggregator-group
aggregator.kafka.consumer.poll-timeout-ms=500
aggregator.kafka.consumer.enable-auto-commit=false
aggregator.kafka.consumer.auto-offset-reset=earliest

aggregator.kafka.close-timeout-seconds=30
aggregator.kafka.retries=3

