spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.sensors-topic=telemetry.sensors.v1
spring.kafka.snapshots-topic=telemetry.snapshots.v1
spring.kafka.consumer-group-id=aggregator-group
spring.kafka.close-timeout-seconds=30
spring.kafka.poll-timeout-millis=500
spring.kafka.retries=3
